name: MCP Tool CI/CD

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'mcp-tool/**'
      - '.github/workflows/mcp-tool-ci.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'mcp-tool/**'
      - '.github/workflows/mcp-tool-ci.yml'
  workflow_dispatch:

jobs:
  test:
    name: Test & Build
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: mcp-tool/package-lock.json

      - name: Install dependencies
        working-directory: mcp-tool
        run: npm ci

      - name: Build
        working-directory: mcp-tool
        run: npm run build

      - name: Check build output
        working-directory: mcp-tool
        run: |
          ls -la build/
          file build/index.js

  publish:
    name: Publish Package
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        working-directory: mcp-tool
        run: npm ci

      - name: Build
        working-directory: mcp-tool
        run: npm run build

      - name: Create tarball
        working-directory: mcp-tool
        run: npm pack

      - name: Upload tarball artifact
        uses: actions/upload-artifact@v4
        with:
          name: mcp-tool-package
          path: mcp-tool/*.tgz
          retention-days: 30
